version: "3.9"

services:
    user:
        build: user-service
        environment:
            PAYMENT_HOST: "payment:8055"
        ports:
            - "8081:8081"
        depends_on:
            - payment
        restart: always
    payment:
        build: payment-service
        ports:
            - "8055:8055"
        restart: always
